### PR TITLE
The 5 task from introduction 

### PR DESCRIPTION
**Pull request by KalinGv**
In the readme file there are the names of the html files of every task.

### CODE REVIEW

**Comment by mgenov** [comment]
Please squash your commits.

You can do it with: 
```
git fetch upstream
git rebase upstream/master
```

**Comment by KalinGv** [comment]
ok

**Comment by KalinGv** [comment]
When i tried to squash my commits somehow they've been added as new  commits at the top of the old ones. I don't know what why that happened. Is it because they are added from another repo to the fork? Will it be better to redo all the commits from scratch?

**Comment by mgenov** [comment]
I suppose you have taken another branch as a source.

Here are some notes which you may consider:
1) You are using master for future development
2) You have no started from upstream/master

Here are some guidelines:

```
# Copy task files in temporary folders
mkdir ~/tmp/
cp -fr * ~/tmp/

# Make a new clean branch from upstream/master
git fetch upstream
git checkout -b html_intro upstream/master

# Restore task files into the branch
cp -fr ~/tmp/* .

# Commit your changes
git add .
git commit
```

**Comment by KalinGv** [comment]
I'll give that a try.

**Comment by KalinGv** [comment]
Maybe I'm not doing it properly. The same thing keeps happening again. I think it will be better to redo my commits one by one. It would be less comfuseing and form now on I'll be squashing my commits before adding them into master.

**Pull request closed without merging**
